### ISSUE TITLE
Headphone output distorted on default layout

### ISSUE THREAD

**Issue by Horseface94** [TokiharaSay/OpenCore-RedmiBook14-Hackintosh#1]
Layout 11 set in config.plist by default; headphone output sounds distorted unless balance slider is set to the extreme left or right

Layout 5, 13, 14, 16 - same problem or has bad noise

Layout 17 seems to be good; audio output through headphone sounds fine; will use this for now. Internal speaker and mic works too.

Have not tested other layouts than the above

**Comment by TokiharaSay** [comment]
OK, thank you for providing, but I have no equipment test. I will modify the Layout to 17 after the release of the official version of 0.7.1

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月28日 19:53
收件人: ***@***.***>
抄送: ***@***.***>
主题: [TokiharaSay/OpenCore-RedmiBook14-Hackintosh] Headphone output distorted on default layout (#1)


Layout 11 set in config.plist by default; headphone output sounds distorted unless balance slider is set to the extreme left or right

Layout 5, 13, 14, 16 - same problem or has bad noise

Layout 17 seems to be good; audio output through headphone sounds fine; will use this for now. Internal speaker and mic works too.

Have not tested other layouts than the above

―
